Repository PoFoLo/PoFoLo-FE, pull requests merged in 2024-12, with the labels that each got.

#7 [Feat] 온보딩 페이지 UI 구현 / 반응형 설정 구축
  package-lock.json
  package.json
  src/App.tsx
  src/assets/videos/About/pofoloLogo.mp4
  src/assets/webps/About/about1.webp
  src/assets/webps/About/about1Blue.webp
  src/assets/webps/About/about2.webp
  src/assets/webps/About/about2Blue.webp
  src/assets/webps/About/about3.webp
  src/assets/webps/About/about3Blue.webp
  src/assets/webps/About/contents.webp
  src/assets/webps/About/ipad.webp
  src/assets/webps/About/macbook.webp
  src/components/About/MockUp/index.tsx
  src/components/About/MockUp/styles.ts
  src/components/About/Motivation/MotivationCard/index.tsx
  src/components/About/Motivation/index.tsx
  src/components/About/Motivation/styles.ts
  src/components/About/Title/index.tsx
  src/components/About/Title/styles.ts
  src/constants/About/motivationData.ts
  src/hooks/useResponsive.ts
  src/pages/About/AboutPage/index.tsx
  src/pages/About/AboutPage/styles.ts
  src/styles/theme.ts
Labels: Design 💄, Feat ✨

#8 [Feat] 포트폴리오 상세 페이지 UI 구현
  src/App.tsx
  src/assets/webps/About/macbook.webp
  src/assets/webps/PortfolioDetail/linkBlue.webp
  src/components/About/MockUp/styles.ts
  src/components/About/Motivation/styles.ts
  src/components/About/Title/styles.ts
  src/components/Common/Button/index.tsx
  src/components/Common/Button/styles.ts
  src/components/Common/Detail/styles.ts
  src/components/PortfolioDetail/PortfolioContent/index.tsx
  src/components/PortfolioDetail/PortfolioContent/styles.ts
  src/components/ProjectDetail/Comment/CommentInput/index.tsx
  src/components/ProjectDetail/Comment/CommentItem/index.tsx
  src/components/ProjectDetail/Comment/styles.ts
  src/components/ProjectDetail/ProjectContent/index.tsx
  src/components/ProjectDetail/ProjectContent/styles.ts
  src/hooks/useResponsive.ts
  src/pages/Portfolio/PortfolioDetailPage/index.tsx
  src/pages/Portfolio/PortfolioDetailPage/styles.ts
  src/styles/theme.ts
Labels: Design 💄, Feat ✨

#9 [Feat] Kakao Login 로직 구현 / OAuthLoading 페이지 UI 구현
  package-lock.json
  package.json
  public/favicon.png
  src/App.tsx
  src/apis/instance.ts
  src/assets/webps/Login/pofoloLogo.webp
  src/assets/webps/Login/pofoloLogoOpacity.webp
  src/components/About/MockUp/index.tsx
  src/pages/Login/Join/index.tsx
  src/pages/Login/Join/styles.ts
  src/pages/Login/OAuthLoading/index.tsx
  src/pages/Login/OAuthLoading/styles.ts
Labels: API 👽, Design 💄, Feat ✨

#10 [Feat] WriteProject 페이지 반응형 구현
  src/assets/svgs/WriteProject/imageUploadBtn.svg
  src/assets/svgs/WriteProject/imageUploadPCBtn.svg
  src/components/Common/CheckBox/styles.ts
  src/components/Common/Input/styles.ts
  src/components/Common/Modal/index.tsx
  src/components/Common/Modal/styles.ts
  src/components/Common/TextArea/styles.ts
  src/components/FormField/CategorySection/index.tsx
  src/components/FormField/CategorySection/styles.ts
  src/components/FormField/HeaderSection/index.tsx
  src/components/FormField/HeaderSection/styles.ts
  src/components/FormField/styles.ts
  src/components/WriteProject/ImageSection/index.tsx
  src/components/WriteProject/ImageSection/styles.ts
  src/components/WriteProject/LinkSection/styles.ts
  src/pages/Project/WriteProjectPage/styles.ts
  src/styles/theme.ts
Labels: Design 💄, Feat ✨

#13 [Feat] Join 페이지 UI 구현 / 회원가입 API 연결
  src/assets/svgs/Login/leftBlue.svg
  src/assets/webps/Login/nextBlue.webp
  src/assets/webps/Login/nextWhite.webp
  src/assets/webps/Navbar/navbarLogo.webp
  src/components/Common/Button/index.tsx
  src/components/Common/Input/index.tsx
  src/components/FormField/CategorySection/index.tsx
  src/components/FormField/CategorySection/styles.ts
  src/components/Layout/Navbar/styles.ts
  src/pages/Login/Join/index.tsx
  src/pages/Login/Join/styles.ts
  src/pages/Login/OAuthLoading/index.tsx
Labels: API 👽, Design 💄, Feat ✨

#11 [Feat] writePortfolio 페이지 반응형 UI 구현
  src/assets/svgs/WritePortfolio/projectAddBtn.svg
  src/assets/svgs/WritePortfolio/projectAddPCBtn.svg
  src/assets/webps/Common/modalClose.webp
  src/components/WritePortfolio/NameSection/index.tsx
  src/components/WritePortfolio/ProjectSection/ProjectCard/styles.ts
  src/components/WritePortfolio/ProjectSection/ProjectModal/ModalProjectCard/index.tsx
  src/components/WritePortfolio/ProjectSection/ProjectModal/ModalProjectCard/styles.ts
  src/components/WritePortfolio/ProjectSection/ProjectModal/index.tsx
  src/components/WritePortfolio/ProjectSection/ProjectModal/styles.ts
  src/components/WritePortfolio/ProjectSection/index.tsx
  src/components/WritePortfolio/ProjectSection/mockData.ts
  src/components/WritePortfolio/ProjectSection/styles.ts
  src/pages/Portfolio/WritePortfolioPage/index.tsx
  src/pages/Portfolio/WritePortfolioPage/styles.ts
Labels: Design 💄, Feat ✨

#12 [Feat] 마이페이지 프로필 수정 모달 UI 구현
  src/App.tsx
  src/components/Mypage/EditProfileModal/AvailabilitySection/index.tsx
  src/components/Mypage/EditProfileModal/AvailabilitySection/styles.ts
  src/components/Mypage/EditProfileModal/CheckboxInput/index.tsx
  src/components/Mypage/EditProfileModal/CheckboxInput/styles.ts
  src/components/Mypage/EditProfileModal/ContactSection/index.tsx
  src/components/Mypage/EditProfileModal/ContactSection/styles.ts
  src/components/Mypage/EditProfileModal/EducationSection/index.tsx
  src/components/Mypage/EditProfileModal/IntroductionSection/index.tsx
  src/components/Mypage/EditProfileModal/NicknameSection/index.tsx
  src/components/Mypage/EditProfileModal/ProfileImageSection/index.tsx
  src/components/Mypage/EditProfileModal/ProfileImageSection/styles.ts
  src/components/Mypage/EditProfileModal/ProfileLinkSection/index.tsx
  src/components/Mypage/EditProfileModal/ProfileLinkSection/styles.ts
  src/components/Mypage/EditProfileModal/index.tsx
  src/components/Mypage/EditProfileModal/styles.ts
  src/pages/Mypage/index.tsx
  src/styles/theme.ts
Labels: Design 💄, Feat ✨

#15 [Feat] JoinPage 반응형 구현 / refresh token 로직 추가
  src/apis/instance.ts
  src/components/Common/Input/index.tsx
  src/components/Common/Input/styles.ts
  src/components/FormField/CategorySection/index.tsx
  src/pages/Login/Join/index.tsx
  src/pages/Login/Join/styles.ts
  src/pages/Login/OAuthLoading/index.tsx
Labels: BugFix 🐛, API 👽, Design 💄, Feat ✨

#18 [Feat] writeProject 페이지 API 연결 및 디자인 수정
  src/components/Common/Input/index.tsx
  src/components/Common/Input/styles.ts
  src/components/Common/TextArea/styles.ts
  src/components/FormField/CategorySection/styles.ts
  src/components/WriteProject/ImageSection/index.tsx
  src/components/WriteProject/LinkSection/index.tsx
  src/components/WriteProject/LinkSection/styles.ts
  src/pages/Login/Join/styles.ts
  src/pages/Project/WriteProjectPage/index.tsx
Labels: API 👽, Design 💄, Feat ✨

#5 [Feat] Developed MainPage UI with features including animation on Sor…
  package-lock.json
  src/assets/webps/Main/activeIcon.webp
  src/assets/webps/Main/activeIconMobile.webp
  src/assets/webps/Main/commentFilled.webp
  src/assets/webps/Main/filledLike.webp
  src/assets/webps/Main/filterIconTabletMobile.webp
  src/assets/webps/Main/filterLine2Checked.webp
  src/assets/webps/Main/filterLine2Unchecked.webp
  src/assets/webps/Main/floatingBtn.webp
  src/assets/webps/Main/inactiveIcon.webp
  src/assets/webps/Main/inactiveIconHover.webp
  src/assets/webps/Main/likeFilled.webp
  src/assets/webps/Main/sortCaret.webp
  src/assets/webps/Main/sortIconTabletMobile.webp
  src/assets/webps/Main/testImage.webp
  src/assets/webps/MyPage/myPageEmail.webp
  src/assets/webps/MyPage/myPagePhone.webp
  src/components/Layout/Navbar/styles.ts
  src/components/Main/CardList/Card/index.tsx
  src/components/Main/CardList/Card/styles.ts
  src/components/Main/CardList/index.tsx
  src/components/Main/CardList/styles.ts
  src/components/Main/FilterBar/FilterBarPC/SubFilterBar/FilterDetail/index.tsx
  src/components/Main/FilterBar/FilterBarPC/SubFilterBar/FilterDetail/styles.ts
  src/components/Main/FilterBar/FilterBarPC/SubFilterBar/index.tsx
  src/components/Main/FilterBar/FilterBarPC/SubFilterBar/styles.ts
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/CategoryFilter/index.tsx
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/CategoryFilter/styles.ts
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/SearchBar/index.tsx
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/SearchBar/styles.ts
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/SortDropdown/index.tsx
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/SortDropdown/styles.ts
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/index.tsx
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/styles.ts
  src/components/Main/FilterBar/FilterBarPC/index.tsx
  src/components/Main/FilterBar/FilterBarPC/styles.ts
  src/components/Main/FilterBar/FilterBarTabletMobile/index.tsx
  src/components/Main/FilterBar/FilterBarTabletMobile/styles.ts
  src/components/Main/FilterBar/index.tsx
  src/components/Main/FloatingBtn/index.tsx
  src/components/Main/FloatingBtn/style.ts
  src/components/Main/SearchBar/SubNavbar/index.tsx
  src/components/Main/SearchBar/SubNavbar/styles.ts
  src/pages/Main/MainPage/index.tsx
  src/pages/Main/MainPage/styles.ts
Labels: Design 💄, Feat ✨

#20 [Feat] Project Detail API 연결
  src/App.tsx
  src/apis/instance.ts
  src/assets/webps/Common/projectDefault.webp
  src/components/Common/Detail/styles.ts
  src/components/ProjectDetail/Comment/CommentItem/index.tsx
  src/components/ProjectDetail/Comment/CommentList/index.tsx
  src/components/ProjectDetail/Comment/dto.ts
  src/components/ProjectDetail/Comment/index.tsx
  src/components/ProjectDetail/Comment/styles.ts
  src/components/ProjectDetail/ProjectContent/dto.ts
  src/components/ProjectDetail/ProjectContent/index.tsx
  src/components/ProjectDetail/ProjectContent/styles.ts
  src/pages/Login/Join/index.tsx
  src/pages/Login/OAuthLoading/index.tsx
Labels: API 👽, Design 💄, Feat ✨

#21 [Feat] 프로젝트 수정 api 연결
  src/App.tsx
  src/components/WriteProject/ImageSection/index.tsx
  src/pages/Project/WriteProjectPage/index.tsx
Labels: API 👽

#23 [Feat] 포트폴리오 작성/수정 페이지 api 연결
  src/App.tsx
  src/assets/svgs/Common/defaultPortfolio.png
  src/assets/svgs/Common/defaultProject.svg
  src/components/WritePortfolio/CareerSection/index.tsx
  src/components/WritePortfolio/ProjectSection/ProjectCard/index.tsx
  src/components/WritePortfolio/ProjectSection/ProjectModal/ModalProjectCard/index.tsx
  src/components/WritePortfolio/ProjectSection/ProjectModal/index.tsx
  src/components/WritePortfolio/ProjectSection/index.tsx
  src/components/WritePortfolio/ProjectSection/mockData.ts
  src/pages/Portfolio/WritePortfolioPage/index.tsx
Labels: API 👽

#24 [Remove] Mypage 파일 삭제
  src/assets/svgs/Mypage/defaultProfile.svg
  src/components/Mypage/EditProfileModal/AvailabilitySection/index.tsx
  src/components/Mypage/EditProfileModal/AvailabilitySection/styles.ts
  src/components/Mypage/EditProfileModal/ContactSection/index.tsx
  src/components/Mypage/EditProfileModal/ContactSection/styles.ts
  src/components/Mypage/EditProfileModal/EducationSection/index.tsx
  src/components/Mypage/EditProfileModal/EducationSection/styles.ts
  src/components/Mypage/EditProfileModal/IntroductionSection/index.tsx
  src/components/Mypage/EditProfileModal/NicknameSection/index.tsx
  src/components/Mypage/EditProfileModal/NicknameSection/styles.ts
  src/components/Mypage/EditProfileModal/ProfileImageSection/index.tsx
  src/components/Mypage/EditProfileModal/ProfileImageSection/styles.ts
  src/components/Mypage/EditProfileModal/ProfileLinkSection/index.tsx
  src/components/Mypage/EditProfileModal/ProfileLinkSection/styles.ts
  src/components/Mypage/EditProfileModal/index.tsx
  src/components/Mypage/EditProfileModal/styles.ts
  src/pages/Mypage/index.tsx
Labels: BugFix 🐛

#25 [Feat] Portfolio Detail API 연결
  src/App.tsx
  src/assets/svgs/Mypage/defaultProfile.svg
  src/assets/webps/MyPage/defaultPortfolioThumbnail.webp
  src/assets/webps/MyPage/defaultProfileImg.webp
  src/assets/webps/MyPage/defaultProjectThumbnail.webp
  src/assets/webps/MyPage/editProfileMobile.webp
  src/assets/webps/MyPage/emailIcon.webp
  src/assets/webps/MyPage/linkIcon.webp
  src/assets/webps/MyPage/myPageEmail.webp
  src/assets/webps/MyPage/myPagePhone.webp
  src/assets/webps/MyPage/offerIcon.webp
  src/assets/webps/MyPage/phoneIcon.webp
  src/assets/webps/MyPage/uploadMyPage.webp
  src/components/MyPage/MyPageCardList/MyPageCard/index.tsx
  src/components/MyPage/MyPageCardList/MyPageCard/styles.ts
  src/components/MyPage/MyPageCardList/index.tsx
  src/components/MyPage/MyPageCardList/styles.ts
  src/components/MyPage/MyPageFilterDetail/index.tsx
  src/components/MyPage/MyPageFilterDetail/styles.ts
  src/components/MyPage/Profile/index.tsx
  src/components/MyPage/Profile/styles.ts
  src/components/MyPage/TabNavigation/index.tsx
  src/components/MyPage/TabNavigation/styles.ts
  src/components/PortfolioDetail/PortfolioContent/dto.ts
  src/components/PortfolioDetail/PortfolioContent/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/styles.ts
Labels: API 👽

#19 [Feat] Initial Version of 'Responsive' Navbar
  src/App.tsx
  src/assets/webps/Common/logoutIcon.webp
  src/assets/webps/Common/navbarHamburger.webp
  src/assets/webps/Common/navbarLogoFull.webp
  src/assets/webps/Common/navbarLogoTabletMobile.webp
  src/assets/webps/MyPage/defaultPortfolioThumbnail.webp
  src/assets/webps/MyPage/defaultProfileImg.webp
  src/assets/webps/MyPage/defaultProjectThumbnail.webp
  src/assets/webps/MyPage/editProfileMobile.webp
  src/assets/webps/MyPage/emailIcon.webp
  src/assets/webps/MyPage/linkIcon.webp
  src/assets/webps/MyPage/offerIcon.webp
  src/assets/webps/MyPage/phoneIcon.webp
  src/assets/webps/MyPage/uploadMyPage.webp
  src/components/Layout/Navbar/Navbar.tsx
  src/components/Layout/Navbar/NavbarPC.tsx
  src/components/Layout/Navbar/NavbarTabletMobile.tsx
  src/components/Layout/Navbar/index.tsx
  src/components/Layout/Navbar/styles.ts
  src/components/MyPage/EditProfileModal/CheckboxInput/index.tsx
  src/components/MyPage/EditProfileModal/CheckboxInput/styles.ts
  src/components/MyPage/EditProfileModal/ContactSection/index.tsx
  src/components/MyPage/EditProfileModal/ContactSection/styles.ts
  src/components/MyPage/MyPageCardList/MyPageCard/index.tsx
  src/components/MyPage/MyPageCardList/MyPageCard/styles.ts
  src/components/MyPage/MyPageCardList/index.tsx
  src/components/MyPage/MyPageCardList/styles.ts
  src/components/MyPage/MyPageFilterDetail/index.tsx
  src/components/MyPage/MyPageFilterDetail/styles.ts
  src/components/MyPage/Profile/index.tsx
  src/components/MyPage/Profile/styles.ts
  src/components/MyPage/TabNavigation/index.tsx
  src/components/MyPage/TabNavigation/styles.ts
  src/pages/About/AboutPage/index.tsx
  src/pages/Login/Join/index.tsx
  src/pages/Main/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/styles.ts
  src/pages/Portfolio/PortfolioDetailPage/index.tsx
  src/pages/Portfolio/WritePortfolioPage/index.tsx
  src/pages/Project/ProjectDetailPage/index.tsx
  src/pages/Project/WriteProjectPage/index.tsx
Labels: Design 💄, Feat ✨

#27 [Feat] 인사팀 view API 연결 / Navbar isLogged props 삭제 / portfolioDetail, projectDetail 수정
  src/App.tsx
  src/components/Layout/Navbar/NavbarPC.tsx
  src/components/Layout/Navbar/NavbarTabletMobile.tsx
  src/components/Layout/Navbar/index.tsx
  src/components/PortfolioDetail/PortfolioContent/dto.ts
  src/components/PortfolioDetail/PortfolioContent/index.tsx
  src/components/ProjectDetail/Comment/CommentItem/index.tsx
  src/components/ProjectDetail/ProjectContent/index.tsx
Labels: BugFix 🐛, API 👽

#28 [Fix] Project Detail 댓글, 좋아요 플로팅 버튼 오류 해결
  src/components/ProjectDetail/Comment/index.tsx
  src/components/ProjectDetail/ProjectContent/index.tsx
  src/pages/Project/ProjectDetailPage/index.tsx
Labels: BugFix 🐛, API 👽

#29 [Fix] likeBtn 내가 좋아요한 프로젝트인지 확인하여 likeRed 반영
  src/components/ProjectDetail/ProjectContent/index.tsx
Labels: BugFix 🐛, API 👽

#31 [Fix] Join JoinPage 전달 데이터 한국어로 변경 / 학력 소속 공개여부 따라 view 처리
  src/components/PortfolioDetail/PortfolioContent/index.tsx
  src/components/ProjectDetail/ProjectContent/index.tsx
  src/pages/Login/Join/index.tsx
Labels: BugFix 🐛, API 👽

#32 [Fix] Build 에러 해결
  src/App.tsx
  src/components/Common/Modal/index.tsx
  src/components/Main/FilterBar/FilterBarPC/TopFilterBar/SearchBar/index.tsx
  src/components/Main/FilterBar/FilterBarPC/index.tsx
  src/components/Main/FilterBar/index.tsx
  src/pages/About/AboutPage/index.tsx
  src/pages/Login/Join/index.tsx
  src/pages/Login/OAuthLoading/index.tsx
  src/pages/Main/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/NotFound/NotFoundPage/index.tsx
  src/pages/Portfolio/PortfolioDetailPage/index.tsx
  src/pages/Portfolio/WritePortfolioPage/index.tsx
  src/pages/Project/ProjectDetailPage/index.tsx
  src/pages/Project/WriteProjectPage/index.tsx
Labels: BugFix 🐛, Refactor ♻️

#35 [Feat] Open Graph 적용 및 Google Analytics 적용
  index.html
  package.json
  public/thumbnail.png
  src/components/MyPage/MyPageFilterDetail/index.tsx
Labels: Feat ✨

#37 [Fix] 마이페이지 ui 및 props 경고 수정
  src/components/MyPage/MyPageCardList/MyPageCard/styles.ts
  src/components/MyPage/MyPageCardList/index.tsx
  src/components/MyPage/MyPageCardList/styles.ts
  src/components/MyPage/MyPageFilterDetail/styles.ts
  src/components/MyPage/TabNavigation/index.tsx
  src/components/MyPage/TabNavigation/styles.ts
  src/pages/MyPage/styles.ts
Labels: BugFix 🐛, Design 💄

#42 [Feat] mobile input 확대 방지
  index.html
Labels: Feat ✨

#44 [Fix] likeBtn 새로고침 시 사라지는 문제 해결
  src/components/ProjectDetail/ProjectContent/index.tsx
Labels: BugFix 🐛

#45 [Fix] project detail page 이미지 object-fit: cover 추가 및 MyPage 말줄임 적용
  src/components/Common/Detail/styles.ts
  src/components/MyPage/MyPageCardList/MyPageCard/styles.ts
  src/components/ProjectDetail/Comment/styles.ts
Labels: BugFix 🐛
